# Generated by Django 2.2.12 on 2021-03-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descritprion',
            new_name='description',
        ),
    ]
